INSERT INTO `permission` VALUES (1, 'add_patient');
INSERT INTO `permission` VALUES (2, 'view_patients');
INSERT INTO `permission` VALUES (4, 'add_user');
INSERT INTO `permission` VALUES (8, 'view_users');
INSERT INTO `permission` VALUES (16, 'logout');
INSERT INTO `permission` VALUES (32, 'notifications');
INSERT INTO `permission` VALUES (64, 'toggle_user');
INSERT INTO `permission` VALUES (128, 'update_patient');
INSERT INTO `permission` VALUES (256, 'load_patient');
INSERT INTO `permission` VALUES (512, 'load_patient_format');
INSERT INTO `permission` VALUES (1024, 'upcoming_for_clerk');
INSERT INTO `permission` VALUES (2048, 'upcoming_for_clinician');
INSERT INTO `permission` VALUES (4096, 'upcoming_for_clerk_submit');
INSERT INTO `permission` VALUES (8192, 'send_invitation');
INSERT INTO `permission` VALUES (16384, 'prior_visits');
INSERT INTO `permission` VALUES (32768, 'view_facilities');
INSERT INTO `permission` VALUES (65536, 'update_facility');
INSERT INTO `permission` VALUES (131072, 'add_facility');
INSERT INTO `permission` VALUES (262144, 'add_clinicians');
INSERT INTO `user_role` VALUES ('Clerk', 292767);
INSERT INTO `user_role` VALUES ('Clerk Manager', 292831);
INSERT INTO `user_role` VALUES ('Facility Admin', 294879);
INSERT INTO `user_role` VALUES ('Nurse Practitioner', 2098);
INSERT INTO `user_role` VALUES ('Physician', 2098);
INSERT INTO `user_role` VALUES ('Site Admin', 262111);
INSERT INTO `patient_status` VALUES (1, 'Long Term Care');
INSERT INTO `patient_status` VALUES (2, 'Skilled Care / New Admission');
INSERT INTO `patient_status` VALUES (3, 'Discharged');
INSERT INTO `patient_status` VALUES (4, 'Assisted Living');
INSERT INTO `facility`(`name`, `address`, `city`, `state`, `zipcode`, `phone_number`, `active`, `num_floors`, `create_user`) VALUES ('Test Facility', '123 Fake St', 'FakeCity', 'MA', '00000', '8888888888', 1, 4, 0);
INSERT INTO `user` (`role`, `first`, `last`, `email`, `phone`, `floor`, `password`, `email_confirmed`, `confirmed_on`, `create_user`, `active`, `invitation_last_sent`) VALUES ('Clerk', 'Test', 'Test', 'test@clerk.com', NULL, '', '$2b$12$SS6AzOKfWfIqe3UuuSUCEOBe2FxgcHxUUBRIvzGovEzM9FfV4Lc6a', 1, NOW(), 0, 1, NOW());
INSERT INTO `user_to_facility`(`user_id`, `facility_id`, `create_user`) VALUES (1, 1, 1);
INSERT INTO `user` (`role`, `first`, `last`, `email`, `phone`, `floor`, `password`, `email_confirmed`, `confirmed_on`, `create_user`, `active`, `invitation_last_sent`) VALUES ('Facility Admin', 'Test', 'Test', 'test@facilityadmin.com', NULL, '', '$2b$12$SS6AzOKfWfIqe3UuuSUCEOBe2FxgcHxUUBRIvzGovEzM9FfV4Lc6a', 1, NOW(), 0, 1, NOW());
INSERT INTO `user_to_facility`(`user_id`, `facility_id`, `create_user`) VALUES (2, 1, 1);
INSERT INTO `user` (`role`, `first`, `last`, `email`, `phone`, `floor`, `password`, `email_confirmed`, `confirmed_on`, `create_user`, `active`, `invitation_last_sent`) VALUES ('Physician', 'Test', 'Test', 'test@physician.com', NULL, '', '$2b$12$SS6AzOKfWfIqe3UuuSUCEOBe2FxgcHxUUBRIvzGovEzM9FfV4Lc6a', 1, NOW(), 0, 1, NOW());
INSERT INTO `user_to_facility`(`user_id`, `facility_id`, `create_user`) VALUES (3, 1, 1);
INSERT INTO `user` (`role`, `first`, `last`, `email`, `phone`, `floor`, `password`, `email_confirmed`, `confirmed_on`, `create_user`, `active`, `invitation_last_sent`) VALUES ('Site Admin', 'Test', 'Test', 'test@siteadmin.com', NULL, '', '$2b$12$SS6AzOKfWfIqe3UuuSUCEOBe2FxgcHxUUBRIvzGovEzM9FfV4Lc6a', 1, NOW(), 0, 1, NOW());