INSERT INTO `permission` VALUES (1, 'add_patient');
INSERT INTO `permission` VALUES (2, 'view_patients');
INSERT INTO `permission` VALUES (4, 'add_user');
INSERT INTO `permission` VALUES (8, 'view_users');
INSERT INTO `permission` VALUES (16, 'logout');
INSERT INTO `permission` VALUES (32, 'notifications');
INSERT INTO `permission` VALUES (64, 'toggle_user');
INSERT INTO `permission` VALUES (128, 'update_patient');
INSERT INTO `permission` VALUES (256, 'load_patient');
INSERT INTO `permission` VALUES (512, 'load_patient_format');
INSERT INTO `permission` VALUES (1024, 'upcoming_for_clerk');
INSERT INTO `permission` VALUES (2048, 'upcoming_for_clinician');
INSERT INTO `permission` VALUES (4096, 'upcoming_for_clerk_submit');
INSERT INTO `permission` VALUES (8192, 'send_invitation');
INSERT INTO `permission` VALUES (16384, 'prior_visits');
INSERT INTO `permission` VALUES (32768, 'view_facilities');
INSERT INTO `permission` VALUES (65536, 'update_facility');
INSERT INTO `permission` VALUES (131072, 'add_facility');
INSERT INTO `permission` VALUES (262144, 'add_clinicians');
INSERT INTO `user_role` VALUES ('Clerk', 292767);
INSERT INTO `user_role` VALUES ('Clerk Manager', 292831);
INSERT INTO `user_role` VALUES ('Facility Admin', 294879);
INSERT INTO `user_role` VALUES ('Nurse Practitioner', 2098);
INSERT INTO `user_role` VALUES ('Physician', 2098);
INSERT INTO `user_role` VALUES ('Site Admin', 262111);
INSERT INTO `patient_status` VALUES (1, 'Long Term Care');
INSERT INTO `patient_status` VALUES (2, 'Skilled Care / New Admission');
INSERT INTO `patient_status` VALUES (3, 'Discharged');
INSERT INTO `patient_status` VALUES (4, 'Assisted Living')